[package]
name = "hypergate-config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
arc-swap.workspace = true
hypergate-core = { path = "../hypergate-core" }
http.workspace = true
ipnet = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.9"

[lints]
workspace = true
